project:
  type: website
  output-dir: docs

website:
  title: "Evelyn Greeves"
  favicon: images/eg_favicon.png
  site-url: evelyngreeves.com
  navbar:
    title: false
    logo: images/eg_logo_nf.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - icon: github
        href: https://github.com/evelyngreeves
      - icon: envelope
        href: mailto:ejg553@york.ac.uk
  page-footer: 
    left: 
      - "Copyright 2024, Evelyn Greeves"
    right: 
      - icon: github
        href: https://github.com/evelyngreeves
      - icon: envelope
        href: mailto:ejg553@york.ac.uk

format:
  html:
    theme:
      - styles.scss
    page-layout: full
    mainfont: Noto Sans

editor: visual

