project:
  type: website
  output-dir: docs

website:
  title: "Evelyn Greeves"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - icon: github
        href: https://github.com/evelyngreeves
      - icon: envelope
        href: mailto:ejg553@york.ac.uk
  page-footer: 
    left: 
      - "Copyright 2023, Evelyn Greeves"
    right: 
      - icon: github
        href: https://github.com/evelyngreeves
      - icon: envelope
        href: mailto:ejg553@york.ac.uk

format:
  html:
    theme:
      - styles.scss
    page-layout: full
    mainfont: Noto Sans

editor: visual

